### ISSUE TITLE
Text Input fields broken in IE11 - AngularJS (Umbraco v7.15.5)

### ISSUE THREAD

**Issue by TFAstudio** [rhythmagency/formulate#193] opened 2021-03-15 22:17 UTC
We upgraded Umbraco and Formulate a little while back but failed to notice at the time that text input fields were no longer rendering in IE11 (when using the Responsive [AngularJS] template. The DIV for the row renders but there's no content in there. No HTML inputs etc.
It seems to be a JS issue, as a cached file seems to be what led us to believe all was well. Shift-refresh cleared that old dependency and revealed the true behaviour of the current code.
Other field types seem fine.
This browser is supported by Microsoft until August and we'd like the forms to keep working until then at least.
Help would be appreciated.
Thanks,
AE

Demo here: https://scoutsvictoria.com.au/contact-us/

**Comment by Nicholas-Westby** [comment] 2021-03-16 01:06
Thanks for reporting this.

I can probably look at this in a week or two if you remind me then. If you would like to submit a pull request, I can get a release out sooner.

**Comment by TFAstudio** [comment] 2021-03-28 22:04
I haven't got the know-how to fix this, but hopefully you can find some capacity to loop back and take a look. Thanks for continuing your involvement in such a great package. AE

**Comment by Nicholas-Westby** [comment] 2021-03-29 03:39
Thanks for the reminder; I should have some time this week, hopefully.

**Comment by Nicholas-Westby** [comment] 2021-03-30 02:16
I think the issue is that you seem to be customizing formulate in some way. I did a diff on the JavaScript and I noticed this in your version:

![Formulate createTextField Function with Customization](https://user-images.githubusercontent.com/5933222/112923298-e2ea6780-90c2-11eb-90aa-97f71677727d.png)

Looks like you are using `startsWith`, which is not supported in IE11: https://caniuse.com/mdn-javascript_builtins_string_startswith

You can see that the fields render find when I try on my local with the latest version of Formulate:

![A Formulate Form Rendered using AngularJS](https://user-images.githubusercontent.com/5933222/112923391-10371580-90c3-11eb-93b0-6124c4dc4abe.png)

Closing this issue now.

**Closed as completed by Nicholas-Westby** 2021-03-30 02:16 UTC

**Comment by rgdagostino** [comment] 2021-04-01 03:02
Thanks for that @Nicholas-Westby .
Changed .startsWith("Location_")) with (field.alias.indexOf("Location_")==0)) and everything worked like a charm.
Damn IE11 :D 
Cheers!
