### ISSUE TITLE
HTML email

### ISSUE THREAD

**Issue by josephine1215** [rhythmagency/formulate#102] opened 2017-07-26 15:54 UTC
Is the email send in html instead of plain text ready? If it able to send different message to admin and user, then it will be great. And with website logo.

**Comment by Nicholas-Westby** [comment] 2017-07-26 15:58
I will be closing this issue as a duplicate of: https://github.com/rhythmagency/formulate/issues/83

Please vote on that issue if you would like to see it. And if you or anybody you know wants to implement that feature, Formulate is open source and pull requests are very much welcome.

**Closed by Nicholas-Westby** 2017-07-26 15:58 UTC
