### ISSUE TITLE
Dragging left to select text closes panel instead

### ISSUE THREAD

**Issue by LeaTark** [rhythmagency/formulate#89] opened 2017-02-21 12:39 UTC
Dragging left to select text in some fields (e.g. Create Folder, Layout, Data Value or Validation) closes the panel instead.

![test](https://cloud.githubusercontent.com/assets/25925693/23165128/7e1ca3a4-f832-11e6-9972-9c9f4de81c0d.gif)

**Comment by Nicholas-Westby** [comment] 2017-02-21 16:16
Thanks for the animation! Really useful for understanding the issue. I will investigate if this is a Formulate or Umbraco core bug (I suspect a core bug).

Which browser/OS are you using?

**Comment by LeaTark** [comment] 2017-02-21 16:32
IE11/Win7

**Comment by LeaTark** [comment] 2017-02-21 16:43
I see the same behaviour in FF 11 but not Chrome 56

**Comment by Nicholas-Westby** [comment] 2017-02-25 22:16
I have confirmed that this is an Umbraco core bug. To reproduce, right click on a content node, select "Copy", then click and drag left pretty much anywhere on the slide out dialog area.

I noticed this only seems to happen with the new style of dialogs (i.e., those created with an HTML file rather than a Web Forms page). I recommend reporting this issue on Umbraco's issue tracker here: http://issues.umbraco.org/dashboard

I'll close this issue since it is not a Formulate bug, but an Umbraco bug.

**Closed by Nicholas-Westby** 2017-02-25 22:16 UTC
